name: libpttea
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/bubble-tea-project/libpttea-dart

environment:
  sdk: ^3.5.4

dependencies:
  logging: ^1.3.0
  ansiparser: ^1.0.2
  big5_utf8_converter: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
